# Generated by Django 6.0.7 on 2026-07-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_options_car_owner_alter_car_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
